### ISSUE TITLE
frozen

### ISSUE THREAD

**Issue by Faris90** [TheColours/Agar-Clone#1]
When I join the game, I can't move :(

**Comment by TheColours** [comment]
It seems your ping is quite high (in the red), I have set the movement speed to be inversely proportional to the ping, in case the location synchronization is seriously distorted.
The reason your ping is high I think is because I chose the photon server in Asia, maybe you are quite far from it, or simply because Photon PUN2 has quite high latency and this project should use Fusion instead. That's it! Sorry for the bad experience! ^^

**Comment by Faris90** [comment]
how do I set that?

**Comment by TheColours** [comment]
I have set up my photon server in Asia. Have you ever used a photon server? It doesn't work well in all areas
